KLEE: Using Z3 solver backend
KLEE: ERROR: goroutine.go:4: failed external call: __go_go
KLEE: NOTE: now ignoring this error at this location
